wordpress:
  hostname: buddy
  # build: .
  image: wordpress
  links:
    - db:mysql
  # depends_on:
  #   - db
  ports:
    - 8080:80
  working_dir: /var/www/html
  volumes:
    - ./wp-content:/var/www/html/wp-content
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: barnabus